import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="flex flex-col gap-4 w-screen h-screen items-center justify-between p-20">
        <h1 className="font-bold text-4xl">Bienvenido al Teatro er Mango</h1>
        {children}
        <footer>Todos los tickes tienen valor de 100$</footer>
      </main>
      </body>
    </html>
  );
}
